# Generated by Django 3.0.2 on 2020-08-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winem', '0002_auto_20200817_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
