# Generated by Django 3.0.2 on 2020-08-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winem', '0005_auto_20200819_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.TextField(default=''),
        ),
    ]
