# Generated by Django 3.0.2 on 2020-08-19 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winem', '0006_game_game_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_id',
        ),
    ]
