# Generated by Django 3.0.2 on 2020-08-20 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('winem', '0009_auto_20200818_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='tie',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='win',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
