# Generated by Django 3.0.2 on 2020-08-22 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winem', '0011_student_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='users',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='winem.Team'),
            preserve_default=False,
        ),
    ]
