# Generated by Django 3.0.2 on 2020-09-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winem', '0012_student_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dorm',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
