# Generated by Django 3.0.2 on 2020-09-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winem', '0014_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
