# Generated by Django 3.0.2 on 2020-09-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winem', '0017_auto_20200912_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abbr',
            field=models.CharField(default='WSH', max_length=3),
            preserve_default=False,
        ),
    ]
